### ISSUE TITLE
Menubuttons verschwunden

### ISSUE THREAD

**Issue by Aha4Kidz** [moziloDasEinsteigerCMS/mozilo2.0#22]
Hallo 
Im Editor sind die Menue-Buttons verschwunden und Mozilo Syntax wird nicht mehr ausgeführt sondern im Browser direkt ausgegeben. Beim Klick auf Speichern/Vorschau wird eine Fehlermeldung angezeigt: "Header:Fehlermeldungen - Body: unbekannter fehler - Footer: Button: Seite neu laden"
Gibt es dafür eine Lösung?

**Comment by marusti** [comment]
Hallo Aha4kidz, ich habe dein Problem im Forum geloggt https://www.mozilo.de/forum/index.php/topic,4358.0.html

**Comment by drdf** [comment]
@Aha4Kidz schau mal, ob unter `Einstellungen > Syntax-Einstellungen > CMS-Syntax nutzen` der Haken gesetzt ist. (Vergleiche: <https://www.mozilo.de/moziloCMS%202.0/Anleitung/Einstellungen.html>)
