### ISSUE TITLE
Cookie Banner mit Zustimmungsbutton integrieren

### ISSUE THREAD

**Issue by FlightMS** [moziloDasEinsteigerCMS/mozilo2.0#29]
Durch die DSGVO ist es notwendig geworden, entsprechend auf Verwendung von Cookies mit möglicher Opt in bzw. Opt out hinzuweisen.

Im MoziloCMS lässt sich dies teilweise über Plugins realisieren. Da dies aber ein Thema ist, welche für nahezu jede Website von Belang sein sollte, wäre eine direkt in MoziloCMS integrierte Lösung sehr hilfreich.

**Comment by marusti** [comment]
Cookie Plugin ist mit Rev-53 integriert. moziloCMS selbst setzt nur ein Session Cookie.
