### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [moziloDasEinsteigerCMS/mozilo2.0#34]
Hey there!

I belong to an open source security research community, and a member (@truonghuuphuc) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by marusti** [comment]
Hi  Jamie,
thanks for getting in touch. You can contact us at kontakt@mozilo.de
Thanks

**Comment by JamieSlome** [comment]
@marusti - thanks for the response! ❤️ 

I have sent an e-mail to the address above...

You can also find the report directly [here](https://huntr.dev/bounties/4e5384f7-8d5b-4b96-a01c-e30c2b3fbefc) 👍
